---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-python-deployment
  labels:
    app: simpleapp-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleapp-python
  template:
    metadata:
      labels:
        app: simpleapp-python
    spec:
      containers:
      - name: simpleapp-python
        image: ezequielsbarros/simpleapp-python:latest
        envFrom:
        - configMapRef:
            name: simpleapp-python
        ports:
        - containerPort: 8008
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 0.5
            memory: 64Mi
          requests:
            cpu: 0.5
            memory: 64Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simpleapp-python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simpleapp-python-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-python-service
spec:
  selector:
    app: simpleapp-python
  ports:
    - port: 8008
      protocol: TCP
      targetPort: 8008
  type: LoadBalancer
   